# Generated by Django 3.2.7 on 2021-10-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('long_url_format', models.URLField(verbose_name='Long Url')),
                ('short_url_format', models.CharField(max_length=15, unique=True, verbose_name='Short Url')),
            ],
            options={
                'ordering': ['made_on'],
            },
        ),
    ]
